donate_index:
    path:     /
    defaults: { _controller: "AppBundle:Donate:new" }
donate_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Donate:show" }

donate_new:
    path:     /new
    defaults: { _controller: "AppBundle:Donate:new" }

donate_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Donate:edit" }

donate_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Donate:delete" }

mesdons:
    path:     /mes-dons
    defaults: { _controller: "AppBundle:Donate:index" }
    methods:  [GET, POST]