event_index:
    path:     /
    defaults: { _controller: "AppBundle:Event:index" }
marathon:
    path:     /marathon
    defaults: { _controller: "AppBundle:Event:indexMarathon" }
event_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Event:show" }

event_new:
    path:     /new
    defaults: { _controller: "AppBundle:Event:new" }

event_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Event:edit" }

event_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Event:delete" }
