team_index:
    path:     /
    defaults: { _controller: "AppBundle:Team:index" }
team_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Team:show" }

team_new:
    path:     /new
    defaults: { _controller: "AppBundle:Team:new" }

team_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Team:edit" }

team_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Team:delete" }
