gallery_index:
    path:     /
    defaults: { _controller: "AppBundle:Gallery:index" }


gallery_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Gallery:show" }

gallery_new:
    path:     /new
    defaults: { _controller: "AppBundle:Gallery:new" }

gallery_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Gallery:edit" }

gallery_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Gallery:delete" }
